[project]
name = "calibration"
version = "0.1.0"
description = "Cognitive Test Calibration"
authors = [
    {name = "Joquin Ordieres-Mere <j.ordieres@upm.es>"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "xgboost (>=3.2.0,<4.0.0)",
    "pandas (>=2.0.0,<3.0.0)",
    "sqlalchemy (>=2.0.0,<3.0.0)",
    "psycopg2-binary (>=2.9.9,<3.0.0)",
    "scikit-learn (>=1.3.0,<2.0.0)",
    "pydantic (>=2.0.0,<3.0.0)",
    "plotly (>=5.0.0,<6.0.0)",
    "openpyxl (>=3.0.0,<4.0.0)",
    "pyyaml (>=6.0,<7.0.0)",
    "python-dotenv (>=1.0.0,<2.0.0)",
    "scipy (>=1.9.0,<2.0.0)",
    "statsmodels (>=0.14.0,<1.0.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pytest = "^9.0.3"
sphinx = "^9.1.0"
sphinx-autodoc-typehints = "^3.2.0"
sphinxcontrib-mermaid = "^2.0.0"
roman-numerals = "^1.0.0"

