import logging
import gettext
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from typing import Dict, Any
from sklearn.metrics import root_mean_squared_error, r2_score

logger = logging.getLogger(__name__)
translation = gettext.translation('messages', localedir='locales', fallback=True)
_ = translation.gettext

class ReportGenerator:
    """Utility class for generating performance reports and interactive visualizations.

    This class encapsulates the logic required to evaluate the regression
    predictions against the clinical gold standard. It calculates standard
    performance metrics and exports the results to both tabular (Excel) 
    and interactive visual (HTML via Plotly) formats, facilitating clinical 
    interpretability and auditing.

    Attributes:
        output_excel (str): The file path where the Excel report will be saved.
        output_html (str): The file path where the Plotly visualization will be saved.
    """

    def __init__(self, output_excel: str, output_html: str) -> None:
        """Initializes the report generator with the desired output paths.

        Args:
            output_excel (str): Destination path for the tabular metrics file.
            output_html (str): Destination path for the interactive plot file.
        """
        self.output_excel = output_excel
        self.output_html = output_html

    def evaluate_and_save(self, y_true: pd.Series, y_pred: Any, model_name: str) -> Dict[str, float]:
        """Calculates regression metrics and appends them to the Excel report.

        This method computes the Root Mean Squared Error (RMSE) and the 
        Coefficient of Determination (R2 Score). It then attempts to read 
        an existing Excel report to append the new results; if the file 
        does not exist, it creates a new one. This allows multiple models 
        in a pipeline to log their results sequentially.

        Args:
            y_true (pd.Series): The ground truth paper-based scores.
            y_pred (Any): The array of predictions generated by the model.
            model_name (str): The identifier of the algorithm evaluated.

        Returns:
            Dict[str, float]: A dictionary containing the computed metrics.
        """
        logger.info(_("Calculando metricas de rendimiento para el modelo %s"), model_name)
        
        rmse = float(root_mean_squared_error(y_true, y_pred))
        r2 = float(r2_score(y_true, y_pred))
        
        metrics = {
            "Model": model_name,
            "RMSE": rmse,
            "R2_Score": r2
        }
        
        logger.info(_("Metricas obtenidas - RMSE: %.4f, R2: %.4f"), rmse, r2)
        
        df_new = pd.DataFrame([metrics])
        
        try:
            df_existing = pd.read_excel(self.output_excel)
            df_final = pd.concat([df_existing, df_new], ignore_index=True)
        except FileNotFoundError:
            df_final = df_new
            
        df_final.to_excel(self.output_excel, index=False)
        logger.info(_("Resultados guardados exitosamente en %s"), self.output_excel)
        
        return metrics

    def generate_scatter_plot(self, y_true: pd.Series, y_pred: Any, model_name: str) -> None:
        """Creates and saves an interactive scatter plot comparing predictions vs truth.

        This visualization plots the predicted digital scores on the Y-axis 
        against the actual paper-based scores on the X-axis. It includes a 
        diagonal reference line representing perfect prediction to help clinicians 
        visually assess the calibration quality and detect potential systemic bias.

        Args:
            y_true (pd.Series): The ground truth paper-based scores.
            y_pred (Any): The array of predictions generated by the model.
            model_name (str): The identifier of the algorithm to title the plot.
        """
        logger.info(_("Generando visualizacion interactiva con Plotly para %s"), model_name)
        
        fig = go.Figure()
        
        fig.add_trace(go.Scatter(
            x=y_true, 
            y=y_pred, 
            mode='markers',
            name=_('Predicciones'),
            marker=dict(size=10, opacity=0.7)
        ))
        
        min_val = min(min(y_true), min(y_pred))
        max_val = max(max(y_true), max(y_pred))
        
        fig.add_trace(go.Scatter(
            x=[min_val, max_val], 
            y=[min_val, max_val], 
            mode='lines', 
            name=_('Referencia Ideal'),
            line=dict(dash='dash', color='red')
        ))
        
        fig.update_layout(
            title=_("Calibracion de %s: Digital vs Papel") % model_name.upper(),
            xaxis_title=_("Puntuacion Real (Test en Papel)"),
            yaxis_title=_("Puntuacion Predicha (Test Digital)"),
            template="plotly_white"
        )
        
        plot_path = self.output_html.replace(".html", f"_{model_name}.html")
        fig.write_html(plot_path)
        logger.info(_("Grafico interactivo exportado en %s"), plot_path)
